-- Exploratory Data Analysis -- 
# Let's start by finding the peak years for nuclear energy generatio in the US
SELECT `YEAR`, `Nuclear Generation` 
FROM us_nuclear_generation1
ORDER BY `Nuclear Generation` DESC;
# 2019 had the highest total amount of energy produced from nuclear power.
# Interestingly, 2020 and 2021 are significantly further down the list, so there has been a decline in the amount of energy produced by nuclear power plants since 2019.

SELECT `YEAR`, `NUCLEAR FUEL SHARE`
FROM us_nuclear_generation1
ORDER BY `NUCLEAR FUEL SHARE` DESC;
# 2001 had the highest nuclear fuel share with recent years being further down the list. This indicates that the US is becoming less dependent on nuclear energy.

# This decline in dependency on nuclear energy may be related to uranium prices so we can compare those two trends over time.

SELECT us_nuclear_generation1.year, us_nuclear_generation1.`NUCLEAR FUEL SHARE`, uranium_price_us.`Total purchased`
FROM us_nuclear_generation1
JOIN uranium_price_us ON us_nuclear_generation1.year = uranium_price_us.`Delivery year`;

#It is clear that the price of uranium has increased significantly since 2002 when nuclear fuel share was at its highest.
# However, the price of uranium has actually declined since 2011 so this is insufficient to explain the lower amounts of nuclear power generated in recent years.

#Let's look now at the nuclear fuel share of the entire world between 2019 and 2024.

SELECT Year, AVG(share_of_generation_pct)
FROM world_electricity_generation
GROUP BY Year;

# Again, we see a similar trend where the importance of nuclear energy has declined in recent years.

# Which countries produced the most nuclear energy in 2023? This is the most recent year for which we have data.

SELECT * 
FROM world_nuclear_energy_generation
WHERE Year = 2023
ORDER BY electricity_from_nuclear_twh DESC;

# When excluding regional categories such as Asia or Europe and just looking at individual countries, it is clear that the US, China, France, Russia and South Korea produce the most nuclear power.

# How much of the world's nuclear power has come from these top 5 countries historically?
WITH top5 AS(
SELECT SUM(electricity_from_nuclear_twh) AS total_from_top5, year
FROM world_nuclear_energy_generation
WHERE Entity IN ('United States', 'France', 'China', 'Russia', 'South Korea')
GROUP BY Year
),
world AS (
SELECT electricity_from_nuclear_twh AS world_total,year
FROM world_nuclear_energy_generation
WHERE Entity = 'World'
)
SELECT world.year, total_from_top5, world.world_total, total_from_top5/world_total*100 AS percent_share
FROM top5
JOIN world on world.year  = top5.year
WHERE world.year >= 1985; # we only have reliable data for most entities after 1985

# The results show that the contribution to the world's total nuclear energy from the 5 biggest producers has increased significantly over time. In 2023, over 72% of the world's nuclear power was generated by these 5 countries.

# Which countries are the most dependent on nuclear energy?
SELECT * 
FROM world_nuclear_energy_generation
WHERE Year = 2023
ORDER BY share_of_electricity_pct DESC;
#Interestingly, this list is quite different to the list of countries which produce the most nuclear energy. However, France is near the top of both lists which underlines their significant investment in nuclear energy.

# What are the major companies operating nuclear power in the US?
SELECT COUNT(`Plant Name, Unit Number`), COUNT(DISTINCT `Parent Company Utility Name`)
FROM reactors_parent_companies;
# There are 21 companies operating 95 nuclear plants in the US.


WITH companies_by_plants AS (
SELECT `Parent Company Utility Name` , COUNT(`Parent Company Utility Name`) AS number_of_plants
FROM reactors_parent_companies
GROUP BY `Parent Company Utility Name`
ORDER BY 2 DESC)

SELECT COUNT(`Parent Company Utility Name`)
FROM companies_by_plants
WHERE number_of_plants >= 5;

WITH companies_by_plants AS (
SELECT `Parent Company Utility Name` , COUNT(`Parent Company Utility Name`) AS number_of_plants
FROM reactors_parent_companies
GROUP BY `Parent Company Utility Name`
ORDER BY 2 DESC)

SELECT 100* SUM(number_of_plants)/95
FROM companies_by_plants
WHERE number_of_plants >= 5;

# The results show that just 7 US companies have more than 5 nuclear plants, accounting for 70.53% of total nuclear generation.
# This shows that there is a significant concentration of the nuclear market in the US.